version: '3'
services:
  frontend:
    build: frontend
    # environment:
    #   - REACT_APP_GOOGLE_RECAPTCHA_KEY=6LfQi64bAAAAAFJJtVQs9BGRDERq4MtM381qFbvy
    #   - REACT_APP_SERVER_URL=http://localhost:5000
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./frontend:/app
    depends_on:
      - backend
  backend:
    build: backend
    ports:
      - '5000:5000'
    # environment:
    #   - CLOUDINARY_HOST=dywtied0r
    #   - CLOUDINARY_API_KEY=282492283825573
    #   - CLOUDINARY_API_SECRET=aGo9UjDf9O3YizdoM49VHcJssQ0
    #   - PORT=5000
    #   - DB_CONNECT=mongodb+srv://masterwork2:masterwork2@cluster0.m8vm7.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
    #   - TOKEN_SECRET=HúDeBetyárTitkosEzAJelszó
    volumes:
      - /app/node_modules
      - ./backend:/app
  open-api-doc:
    build: open-api-doc
    ports:
      - '4000:8080'
    volumes:
      - /app/node_modules
      - ./open-api-doc:/app
